Migration: changes
Paul-tes/Blog-App pull request #1
Opened 2023-08-16 20:52 UTC by Paul-tes

- Created  a new  rails app with the name of **Blog App**
- Added  Postgres database set up.
- Built  project schema.
- Create and run the necessary migration files based ont the [ERD diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png).
- Added user migration
- Added post migration
- Added comment migration
- Added like migration.

2023-08-16 21:11 UTC, Ismailco requested changes
### Hi @Paul-tes, 

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-16 21:11 UTC, Ismailco commented on db/migrate/20230816201738_create_users.rb
> +      # t.datetime :updated_at
- [ ] Kindly make sure to remove all commented code from your code base, it makes your code messy and hard to read

2023-08-16 21:11 UTC, Ismailco commented on README.md
> +- Comming soon
- [ ] Kindly consider removing the `Live Demo` section altogether from your README file until you're planning on deploying the project

2023-08-16 21:11 UTC, Ismailco commented on README.md
> +This project is [MIT](./MIT) licensed.
- [ ] The License is missing on your project kindly make sure to add a license and fix this link so it's not broken

2023-08-16 21:11 UTC, Ismailco commented on db/migrate/20230816202514_create_posts.rb
> +      t.integer :comments_counter
- [ ] Same here kindly make sure to remove commented code

2023-08-16 21:11 UTC, Ismailco commented on db/migrate/20230816202753_create_comments.rb
> +      # t.datetime :updated_at
- [ ]  Same here kindly make sure to remove commented code

2023-08-16 21:11 UTC, Ismailco commented on db/migrate/20230816203245_create_likes.rb
> +      # t.datetime :updated_at
- [ ]  Same here kindly make sure to remove commented code

2023-08-17 07:12 UTC, brainconnect93 requested changes
### Hi @Paul-tes, 👋 

# STATUS: Changes Required :recycle:

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

## Good Points 👍

- Descriptive Pull Request title & summary. ✔️
- Created migration file for `users`, `posts`, `comments` & `likes` ✔️
- Migrate all file to the schema ✔️ 
- Good use of Git flow ✔️

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-17 07:12 UTC, brainconnect93 commented on README.md
> +This project is [MIT](./MIT) licensed.
- [ ] As suggested by the previous reviewer, kindly work on the MIT license link as the link is still not working. I realized you have target the file name wrongly, it should be `./MIT.md`

2023-08-17 08:18 UTC, VICTOR-CHUKWU approved these changes
Hi @Paul-tes , 
# STATUS: APPROVED! 🥇 💯 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [ ] All linters passed

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-17 08:24 UTC, merged