Views rspec and optimization: changes
Paul-tes/Blog-App pull request #8
Opened 2023-08-29 19:48 UTC by Paul-tes

## Optimization
- To overcome the n+1 problem, query optimization is done using the rails active record eager load technique.
> below page is rendered to check the optimization.
![page](https://github.com/Paul-tes/Blog-App/assets/86291500/198475ab-457d-4ff1-a45e-b890d2b7ba50)
> Befor optimization the log data in rails server on puma terminal:
![before](https://github.com/Paul-tes/Blog-App/assets/86291500/897ecf8e-c009-4182-905c-d7670a3b012c)
> After optimization the log data in rails server on puma terminal
![after](https://github.com/Paul-tes/Blog-App/assets/86291500/949fcc72-70a2-480d-8667-c9f61e102986)
## Integration specs
- Useed Capybara to write integration tests for each view in these project.
- Add User index page feature tests with the following test cases:
   - I can see the username of all other users.
   - I can see the profile picture for each user.
   - I can see the number of posts each user has written.
   - When I click on a user, I am redirected to that user's show page.
- Added user show page feature tests with the following test cases:
   - I can see the user's profile picture.
   - I can see the user's username.
   - I can see the number of posts the user has written.
   - I can see the user's bio.
   - I can see the user's first 3 posts.
   - I can see a button that lets me view all of a user's posts.
   - When I click a user's post, it redirects me to that post's show page.
   - When I click to see all posts, it redirects me to the user's post's index page.
- Added User post index page feature tests with the following test cases:
   - I can see the user's profile picture.
   - I can see the user's username.
   - I can see the number of posts the user has written.
   - I can see a post's title.
   - I can see some of the post's body.
   - I can see the first comments on a post.
   - I can see how many comments a post has.
   - I can see how many likes a post has.
   - I can see a section for pagination if there are more posts than fit on the view.
   - When I click on a post, it redirects me to that post's show page.
- Added Post show page feature test for the following test cases:
   - I can see the post's title.
   - I can see who wrote the post.
   - I can see how many comments it has.
   - I can see how many likes it has.
   - I can see the post body.
   - I can see the username of each commentor.
   - I can see the comment each commentor left.

2023-08-29 20:30 UTC, danmainah requested changes
Hi @Paul-tes and @baqar-abbas , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Used Capybara to write integration tests for each view in the project.
✔️ Ensured all tests added are passing.


# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- @Paul-tes It would be nice adding @baqar-abbas information in the authors section as one of the contributors of this project.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-08-29 20:30 UTC, danmainah commented on app/controllers/posts_controller.rb
>    end
- [x] @Paul-tes and @baqar-abbas Great work trying to fix the N + 1 problem, however you did it the wrong way, The project required fixing the query of all the user's posts and comments, that way the query will be faster than the current solution, dont forget to update the screenshot after adding the new solution.
![image](https://github.com/Paul-tes/Blog-App/assets/61408860/f0bb3ff0-c34f-4bdf-b03d-8c0463db46bf)

`hint: in your index method you can add @posts = @user.posts.includes(:comments) to fix the problem`

2023-08-29 20:30 UTC, danmainah commented on spec/future/users_spec.rb
> +  end
- [x] @Team kindly consider changing the title of these tests to reflect what they are testing also ensure all tests for the user show page are added.

- [x] [optional] @Team it would have been nicer if you grouped tests of each page in a single file instead of mixing tests for two views as you have done now for the user and posts pages.

2023-08-29 20:30 UTC, danmainah commented on spec/future/posts_spec.rb
> +
- [ ] @Team you forgot to add a test that asserts you can see who wrote the post.

2023-08-30 05:35 UTC, t-yanick approved these changes
# STATUS: MILESTONE APPROVED :1st_place_medal: 

Hi @Paul-tes and @baqar-abbas , 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Requested changes implemented 👍 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-30 08:01 UTC, merged